name: load-apps

on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - .github/workflows/load-apps.yaml
      - apps/**

jobs:
  load-apps:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
      - id: load-apps
        uses: yuya-takeyama/monotonix/actions/load-apps@main
        with:
          root-dir: apps
          global-config-file-path: apps/monotonix-global.yaml
      - name: Display loaded apps
        run: echo "$APPS_JSON" | jq .
        env:
          APPS_JSON: ${{ steps.load-apps.outputs.result }}
